config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:show, :index]

  resources :events, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :requests, only: [:new, :destroy] do
      member do
        patch :accept, to: "requests#accept", as: :accept_request
        patch :reject, to: "requests#reject", as: :reject_request
      end
    end
  end

  resources :chatrooms, only: [:index, :show, :new, :create, :update] do
    resources :messages, only: [:create]
  end


  resources :hobbies, only: [:index, :show]


end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :asker, class_name: 'User', foreign_key: 'asker_id', required: true
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id', required: true

  has_many :messages, dependent: :destroy

  validates :status, presence: true

  def self.search(query)
    if query.present?
      where("name ILIKE ?", "%#{query}%")
    else
      Chatrooms.all
    end
  end

  def pending?
    status == 'pending'
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def index
    @chatrooms = Chatroom.all
    if params[:search].present?
      @chatrooms = Chatroom.where("name ILIKE ?", "%#{params[:search]}%")
    else
      @chatrooms = Chatroom.all
    end
  end

  def new
    @chatroom = Chatroom.new
    @receiver = User.find(params[:id])
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      redirect_to chatrooms_path, notice: 'Connection requested!'
    else
      render "chatrooms/_new", status: :unprocessable_entity
    end
  end

  def update
    @chatroom = Chatroom.find(params[:id])
    if @chatroom.update(chatroom_params)
      redirect_to  chatrooms_path
    else

      redirect_to  chatrooms_path
    end
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name, :asker_id, :receiver_id, :status)
  end
end

app/views/chatrooms/_new.html.erb
<div class="modal fade" id="chatroomAddModal" tabindex="-1" aria-labelledby="chatroomAddModalLabel" aria-hidden="true" >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content ">
          <div class="modal-header">
            <h5 class="modal-title" id="chatroomAddModalLabel">Connect?</h5>
            <button type="button" class="btn-close ml-0" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="d-flex justify-content-center">
            <% if @user.photo.attached? %>
              <%= cl_image_tag(@user.photo.key, class: "avatar-large border") %>
              <% else %>
              <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "avatar-large border") %>
            <% end %>

              <div class="icon-container icons-selected">
              <img src="" data-matching-modal-target="image" class= "hobby-icons">
            </div>
              <% if current_user.photo.attached? %>
                <%= cl_image_tag(current_user.photo.key, class: "avatar-large border") %>
                <% else %>
              <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "avatar-large border") %>

              <% end %>
            </div>

          </div>
          <% if Chatroom.exists?(asker_id: current_user.id, receiver_id: @user.id) || Chatroom.exists?(asker_id: @user.id, receiver_id: current_user.id) %>
            <% if @chatroom.status == "pending" %>
              <p class="text-center">Still waiting for confirmation of the connection.</p>
            <% elsif @chatroom.status == "accepted"%>
              <p class="text-center">You and <%= @user.username %> are already buddies.</p>
              <% end %>
            <% else %>
            <%= simple_form_for @new_chatroom do |f| %>
              <%= f.hidden_field :name, value: "#{current_user.username} + #{@user.username}" %>
              <%= f.hidden_field :asker_id, value: current_user.id %>
              <%= f.hidden_field :receiver_id, value: @user.id %>
              <%= f.submit class:"btn btn-form btn-confirm mt-3", value: "Confirm"%>
            <% end %>
            <% end %>
        </div>
      </div>
    </div>

app/views/chatrooms/index.html.erb
<div class="container">
  <div class="header-and-search">
    <%= form_tag chatrooms_path, method: :get, class: "search-bar" do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Buddies", class: "search-input", autocomplete: "off" %>
      <%= button_tag type: 'submit', class: "search-button" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
  </div>

  <div class="chatroom_card">
    <div class="chatroom_cards">
    <% @chatrooms.select { |chatroom| chatroom.asker == current_user || chatroom.receiver == current_user }.each do |chatroom| %>
      <% user = nil %>
      <% if chatroom.receiver == current_user %>
        <% user = chatroom.asker %>
      <% else %>
        <% user = chatroom.receiver %>
      <% end %>

      <% unless chatroom.status == "rejected" %>
      <% card_link = nil %>
      <% if chatroom.status == "accepted" %>
      <% card_link = chatroom_path(chatroom) %>
      <% elsif chatroom.status == "pending" %>
      <% card_link = current_user == chatroom.asker ? user_path(chatroom.receiver) : user_path(chatroom.asker) %>
      <% end %>

        <%= link_to card_link, class: "full-card-link", data: { controller: "card-click", action:"click->card-click#click" } do %>
          <div class="container-chatroom d-flex align-items-center">
            <div class="avatar-container m-3">
              <% if user.photo.attached? && chatroom.status != "rejected" %>
                <%= cl_image_tag(user.photo.key, class: "avatar") %>
              <% else %>
                <% unless chatroom.status == "rejected" %>
                  <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "avatar") %>
                <% end %>
              <% end %>
            </div>

            <div class="details-container mt-3">
              <div class="links-container">
                <% if chatroom.status == "accepted" %>
                  <% if chatroom.asker == current_user %>
                    <%= user.username %>
                  <% else %>
                    <%= user.username %>
                  <% end %>
                  <i class="fa-sharp fa-solid fa-comment"></i>
                <% end %>
              </div>
              <% if chatroom.status == "accepted" %>
                <% last_message = chatroom.messages.last %>
                <% if last_message %>
                  <p class="last-message-preview"><%= last_message.content %></p>
                <% end %>
              <% elsif chatroom.pending? %>
                <% if chatroom.receiver == current_user %>
                  <%= user.username %>
                  <div class="d-flex justify-content-right a-r-btn">
                    <%= simple_form_for chatroom do |f| %>
                      <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
                      <%= f.submit "✔️"%>
                    <% end %>
                    <%= simple_form_for chatroom do |f| %>
                      <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
                      <%= f.submit "✖️"%>
                    <% end %>
                  </div>
                <% elsif chatroom.asker == current_user %>
                  <p class="mr-3"><%= chatroom.receiver.username %></p>
                  <em><%= "Waiting for #{chatroom.receiver.username} to confirm the connection" %></em>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>

app/views/chatrooms/show.html.erb
<body>
  <%= link_to '/chatrooms', class: "back-button" do %>
    <i class="fa-sharp fa-solid fa-circle-arrow-left"></i>
  <% end %>

  <div class="container chatroom"
    data-controller="chatroom-subscription"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">

    <div class="avatar_and_name">

    <% if @chatroom.asker == current_user %>
      <%= link_to user_path(@chatroom.receiver) do %>
        <h1>
          <% if @chatroom.receiver.photo.attached? %>
          <%= cl_image_tag(@chatroom.receiver.photo.key, class: "chat_avatar")  %>
          <%= @chatroom.receiver.username %>
          <% else %>
          <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "chat_avatar") %>
          <%= @chatroom.receiver.username %>
        </h1>
            <% end %>
      <% end %>
    <% else %>
      <%= link_to user_path(@chatroom.asker) do %>
        <h1>
          <% if @chatroom.asker.photo.attached? %>
          <%= cl_image_tag(@chatroom.asker.photo.key, class: "chat_avatar")  %>
          <%= @chatroom.asker.username %>
          <% else %>
          <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "chat_avatar") %>
          <%= @chatroom.asker.username %>
        </h1>
          <% end %>
      <% end %>
    <% end %>

    </div>

    <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>

    <%= simple_form_for [@chatroom, @message],
      html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f| %>
      <%= f.input :content,
        label: false,
        placeholder: "Message your new buddy here...",
        wrapper_html: { data: { chatroom_subscription_target: "input" }, class: "flex-grow-1" }
      %>
      <%= f.submit "Send", class: "btn btn-primary mb-3 send-btn" %>
    <% end %>
  </div>
</body>