config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:show, :index]

  resources :events, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :requests, only: [:new, :destroy] do
      member do
        patch :accept, to: "requests#accept", as: :accept_request
        patch :reject, to: "requests#reject", as: :reject_request
      end
    end
  end

  resources :chatrooms, only: [:index, :show, :new, :create, :update] do
    resources :messages, only: [:create]
  end


  resources :hobbies, only: [:index, :show]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :location, language: :en
  after_validation :geocode, if: :will_save_change_to_location?

  has_many :chatrooms_as_asker, class_name: "Chatroom", foreign_key: :asker_id, dependent: :destroy
  has_many :chatrooms_as_receiver, class_name: "Chatroom", foreign_key: :receiver_id, dependent: :destroy
  has_many :selected_hobbies
  has_many :hobbies, through: :selected_hobbies
  has_many :events
  has_many :requests
  has_one_attached :photo

  validates :username, :birthdate, :location, :bio, presence: true
  validates :username, uniqueness: true, length: { in: 2..10 }
  validates :bio, length: { in: 20..200 }
  validate :validate_age


  def self.search(query)
    if query.present?
      where("username ILIKE ?", "%#{query}%")
    else
      User.all
    end
  end



  def chatrooms
    chatrooms_as_asker + chatrooms_as_receiver
  end

  def location_by_city
    address = self.location.split(",")
    "#{address.first}, #{address.last}"
  end

  def has_request?(event)
    Request.find_by(user: self, event: event)
  end

  def has_pending_request?(event)
    Request.find_by(user: self, event: event)&.pending?
  end

  def has_rejected_request?(event)
    Request.find_by(user: self, event: event)&.rejected?
  end

  def has_accepted_request?(event)
    Request.find_by(user: self, event: event)&.accepted?
  end

  private

  def validate_age
    if birthdate.present? && birthdate > 18.years.ago.to_datetime
      errors.add(:birthdate, 'You should be over 18 years old.')
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    params[:user][:hobby_ids] = params[:user][:hobby_ids] - ["0"]
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    params[:user][:hobby_ids] = params[:user][:hobby_ids] - ["0"]
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  protected

  def after_update_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  protected

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #def index
    #if params[:search].present?
    #  @users = User.near(current_user.location, 10).joins(:hobbies).distinct.where(hobbies: { name: params[:search].capitalize })
   # else
    #  @users = User.near(current_user.location, 10).joins(:hobbies).distinct.where(hobbies: { id: current_user.hobbies.ids })
   # end
 #end

  def index
  if params[:search].present?
    query = params[:search].capitalize

    @users = User.near(current_user.location, 10).joins(:hobbies).where("users.username LIKE ? OR hobbies.name = ?", "%#{query}%", query).distinct
  else
    @users = User.near(current_user.location, 10).joins(:hobbies).where(hobbies: { id: current_user.hobbies.ids }).distinct
  end
end

  def show
    @user = User.find(params[:id])
    @event = Event.new
    @events = @user.events
    @requests = Request.where(user_id: current_user.id)
    @hobbies = @user.hobbies
    @chatroom = Chatroom.find_by(asker_id: current_user.id, receiver_id: @user.id)|| Chatroom.find_by(asker_id: @user.id, receiver_id: current_user.id)
    @new_chatroom = Chatroom.new
  end
end

app/views/users/index.html.erb
<div class="container">
  <div class="header-and-search">
    <%= form_tag users_path, method: :get, class: "searchbar" do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search for new buddies", class: "search-input", autocomplete: "off" %>
      <%= button_tag type: 'submit', class: "search-button" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
    <br>
  </div>
  <div >
    <p class="index-text-top"><em>Others near you...</em></p>
  </div>
  <div class="user-cards-container">
    <% @users.each do |user| %>
      <% if user != current_user %>
        <div class="user-card">
          <%= link_to user_path(user, from: "all_users"), class:"user-card-link" do %>
            <div class="avatar">
              <h2 class="username"><%= user.username %></h2>
              <% if user.photo.attached? %>
                <%= cl_image_tag(user.photo.key, class: "card-avatar-large") %>
              <% else %>
                <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "card-avatar-large") %>
              <% end %>
            </div>
            <div class="user-details">
              <div class="user-hobby-icons-container">
                <% user.hobbies.each do |hobby| %>
                  <% if hobby.photo.attached? && @user != current_user && current_user.hobbies.include?(hobby) %>
                    <div class="user-hobby-icon-bg icons-selected">
                      <%= cl_image_tag hobby.photo.key, class: "user-hobby-icons" %>
                    </div>
                  <% else %>
                    <div class="user-hobby-icon-bg">
                      <%= cl_image_tag hobby.photo.key, class: "user-hobby-icons" %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% unless request.referer.nil? %>
  <%= link_to request.referer, class: "back-button" do %>
    <i class="fa-sharp fa-solid fa-circle-arrow-left"></i>
  <% end %>
<% end %>



<div class="d-flex justify-content-between m-3">
 <% if @user == current_user %>
    <h1>My profile</h1>
    <div class="d-flex justify-content-evenly w-25">
      <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, style: "text-decoration: none" do %>
      <i class="fa-solid fa-right-from-bracket"></i>
      <% end %>
      <%= link_to edit_registration_path(current_user) do %>
      <i class="fa-solid fa-user-pen"></i>
      <% end %>
    </div>
  <% end %>
</div>

<div class="container d-flex justify-content-center mt-3">
<div class="img-profile w-50 my-3 d-flex align-items-center">
<% if @user.photo.attached? %>
  <%= cl_image_tag(@user.photo.key, class: "avatar-x-large border") %>
  <% else %>
  <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "avatar-x-large border") %>
<% end %>
</div>

<div class="hobbies-profile d-flex justify-content-end align-items-center flex-wrap" data-controller="matching-modal">
  <% @hobbies.each do |hobby| %>
    <% if hobby.photo.attached? && @user != current_user && current_user.hobbies.include?(hobby) %>
      <div class="icon-container icons-selected">
        <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#chatroomAddModal", action: "click->matching-modal#copy"} do %>
              <%= cl_image_tag(hobby.photo.key, class: "hobby-icons", data: { matching_modal_target: "link" }) %>
        <% end %>
        <%= render "chatrooms/new", chatroom: @chatroom %>
      </div>
    <% else %>
      <div class="icon-container">
        <%= cl_image_tag hobby.photo.key, class: "hobby-icons" %>
      </div>
    <% end %>
  <% end %>
</div>
</div>
<div class= "container m-0.5">
  <h1 style="text-align: left;"><%= @user.username %></h1>
  <% age = Date.today.year - @user.birthdate.year %>
  <% age -= 1 if Date.today.strftime("%m%d") < @user.birthdate.strftime("%m%d") %>
  <p id="age">Age: <%= age %></p>

  <p><i class="fa-solid fa-location-dot"></i> <%= @user.location_by_city %></p>

  <div class="separation-line mb-3"></div>
    <p><%= @user.bio %></p>
  <div class="separation-line mb-3"></div>

    <div class="d-flex justify-content-between align-items-center">
    <h3>Events: </h3>
    <% if @user == current_user %>
      <div class="modal fade" id="eventAddModal" tabindex="-1" aria-labelledby="eventAddModalLabel" aria-hidden="true">
        <%= render "events/new", event: @event %>
      </div>
      <button data-bs-toggle="modal" data-bs-target="#eventAddModal" i class="fa-solid fa-plus "></i></button>
    <% end %>
  </div>

  <p>Created Events: </p>
  <% if @events.length > 0 %>
    <ul class="list-unstyled justify-content-center">
    <% @events.each do |event| %>

      <div class="event-card" data-bs-toggle="modal" data-bs-target="#eventDetailModal<%= event.id %>">
      <div class="d-flex align-items-center">
        <div class="user-hobby-icons-container d-flex p-3">
          <div class="user-hobby-icon-bg">
            <% if event.hobby.photo.attached? %>
              <%= cl_image_tag event.hobby.photo.key , class: "user-hobby-icons"%>
            <% end %>
          </div>
        </div>
        <div >
          <h5><%= event.name%></h5>
          <p><%= event.location_by_city %></p>
          <p><%= event.date.strftime("%d %B %Y") %></p>
        </div>
      </div>
      </div>
      <div class="modal fade" id="eventDetailModal<%= event.id %>" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true" data-controller="edit-event">
        <%= render "events/event_modal", event: event%>
      </div>
    <% end %>
    </ul>
  <% else %>
    <p style="color: grey !important"><em>no events created yet</em></p>
  <% end %>
  <% if @user == current_user %>
    <p>Events I'm attending:</p>
    <% if @requests.length > 0 %>
      <% @requests.each do |request| %>
        <% if request.accepted?%>
          <div class="event-card" data-bs-toggle="modal" data-bs-target="#eventDetailModal<%= request.event.id %>">
            <div class="d-flex align-items-center">
              <div class="user-hobby-icons-container d-flex p-3">
                <div class="user-hobby-icon-bg">
                  <% if request.event.hobby.photo.attached? %>
                    <%= cl_image_tag request.event.hobby.photo.key , class: "user-hobby-icons"%>
                  <% end %>
                </div>
              </div>
              <div>
                <h5><%= request.event.name%></h5>
                <p><%= request.event.location_by_city %></p>
                <p><%= request.event.date.strftime("%d %B %Y") %></p>
              </div>
            </div>
          </div>
          <div class="modal fade" id="eventDetailModal<%= request.event.id %>" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true" data-controller="edit-event">
            <%= render "events/event_modal", event: request.event %>
          </div>
        <% end %>
      <% end %>
    <% else %>
    <p style="color: grey !important"><em>no events attended yet</em></p>
    <% end %>
  <% end %>
        </div>

</div>
</div>