config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:show, :index]

  resources :events, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :requests, only: [:new, :destroy] do
      member do
        patch :accept, to: "requests#accept", as: :accept_request
        patch :reject, to: "requests#reject", as: :reject_request
      end
    end
  end

  resources :chatrooms, only: [:index, :show, :new, :create, :update] do
    resources :messages, only: [:create]
  end


  resources :hobbies, only: [:index, :show]


end

app/models/event.rb
class Event < ApplicationRecord

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  belongs_to :user
  belongs_to :hobby
  has_many :requests, dependent: :destroy


  validates :name, :date, :description, :location, presence: true
  validates :description, length: { in: 20..100 }

  def self.search(query)
    if query.present?
      where("name ILIKE ?", "%#{query}%")
    else
      @events = Event.all
    end
  end


  def location_by_city
    address = self.location.split(",")
    "#{address.first}, #{address.last}"
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    if params[:search].present?
      @events = Event.near(current_user.location, 10).joins(:hobby).where("events.name ILIKE ? OR hobbies.name ILIKE ?", "%#{params[:search]}%","%#{params[:search]}%")
    elsif params[:hobby_name].present?
      @events = Event.near(current_user.location, 10).joins(:hobby).distinct.where(hobby: { name: params[:hobby_name] })
    else
      @events = Event.near(current_user.location, 10)
    end
  end

  def show
    @event = Event.find(params[:id])
    @request = Request.new
    @requests = @event.requests
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to user_path(current_user), notice: 'Event was successfully created.'
    else
      respond_to do |format|
        format.html { render :new }
        format.turbo_stream { render turbo_stream: turbo_stream.update('eventAddModal', partial: 'events/new', locals: { event: @event }) }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @persisted = @event.update(event_params)
    respond_to do |format|
      format.html { redirect_to user_path(current_user) }
      # format.text { render partial: "events/event_modal", locals: {event: @event}, formats: [:html] }
      format.json
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_path(current_user), notice: "Event successfully deleted!"
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date, :description, :user_id, :hobby_id)
  end
end

app/views/events/_event_modal.html.erb
<% labels = { interested: false, attending: false } %>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div style="width: 100%; text-align: right; padding: 1px 4px 1px 4px; height: auto">
        <div class="event-modal-header">
          <div class="user-hobby-icons-container d-flex pe-3">
            <div class="user-hobby-icon-bg">
              <% if event.hobby.photo.attached? %>
                <%= cl_image_tag event.hobby.photo.key , class: "user-hobby-icons"%>
              <% end %>
            </div>
          </div>
          <div style="margin: 0; text-align: left; width: 100%">
            <h1 class="modal-title fs-5" style="margin-top: 0; text-align: left" id="eventDetailModalLabel<%= event.id %>" data-model-title="<%= event.name %>"><%= event.name %></h1>
            <% if current_user == event.user %>
              <p style="margin: 0"><em>created by yourself</em></p>
            <% else %>
              <p class="user-link" style="margin: 0"><em>by <%= link_to event.user.username, user_path(event.user.id)%></em></p>
            <% end %>
          </div>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
        </div>
      <div class="separation-line hr hr-blurry" style="background-color: #e3e3e3"></div>
      <div class="modal-body event-infos" data-edit-event-target="infos">
        <p class><b><%= event.date.strftime("%d %B %Y") %></b><br><em><%= event.location_by_city %></em></p>
        <p class="fs-5"><%= event.description %></h5>
      </div>
      <div class="end">
        <% if current_user != event.user %>
          <% if !current_user.has_request?(event) %>
          <div class="interested-btn" style="text-align: center">
            <%= link_to "I'm Interested", new_event_request_path(event), remote: true, method: :get%>
          </div>
          <% elsif current_user.has_pending_request?(event) %>
            <p style="margin-bottom: 0px">Waiting for acceptance</p>
          <% elsif current_user.has_accepted_request?(event) %>
          <div class="d-flex justify-content-between">
            <p style="margin-bottom: 0px">Already attending</p>
            <%= link_to event_request_path(event_id: event.id, id: current_user.requests.find_by(event_id: event.id)&.id) || root_path, data: {turbo_confirm: "Are you sure?", turbo_method: :delete} do %>
              <i class="fa-solid fa-trash-can trash-can" style="color: #a39bf8; margin-left: 6px; font-size: 20px"></i>
            <% end %>
          </div>
          <% elsif current_user.has_rejected_request?(event) %>
            <p style="margin-bottom: 0px">Sorry, we're full</p>
          <% end %>
        <% else %>
          <div class="edit-delete" style="text-align: right; font-size: 20px; color: #a39bf8">
            <i class="fa-solid fa-pen-to-square trash-can" data-action="click->edit-event#displayForm" data-edit-event-target="editButton"></i>
            <%= link_to event_path(event), data: { turbo_confirm: "Are you sure?", turbo_method: :delete } do %>
              <i class="fa-solid fa-trash-can trash-can" style="color: #a39bf8; margin-left: 6px"></i>
            <% end %>
          </div>
          <div data-edit-event-target="labels">
            <% event.requests.each do |request| %>
              <% if request.pending? %>
                <% unless labels[:interested] %>
                  <% labels[:interested] = true %>
                  <p style="margin-top: 10px; margin-bottom: 6px">Interested:</p>
                <% end %>
                <div class="d-flex justify-content-between interested-users" style="border-top: solid 1px #e3e3e3">
                  <div class="d-flex justify-content-left">
                    <% if request.user.photo.attached? %>
                        <%= cl_image_tag(request.user.photo.key, class: "avatar-small") %>
                      <% else %>
                        <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "avatar-small") %>
                      <% end %>
                    <p style="margin-bottom: 0; padding: 0; height: 2rem; line-height: 2rem "><%= link_to request.user.username, user_path(request.user.id) %></p>
                  </div>
                  <div class="d-flex a-r-btn">
                    <p><%= button_to "✔️", accept_request_event_request_path(event, request), method: :patch %></p>
                    <p><%= button_to "✖️", reject_request_event_request_path(event, request), method: :patch %></p>
                  </div>
                </div>
              <% elsif request.accepted? && !request.rejected?%>
              <% unless labels[:attending] %>
                  <% labels[:attending] = true %>
                  <p style="margin-top: 10px; margin-bottom: 6px">Attending:</p>
                <% end %>
                <div class="interested-users" style="border-top: solid 1px #e3e3e3">
                  <%# event.requests.each do |request| %>
                    <% if request.accepted? && !request.rejected?%>
                      <div class="d-flex justify-content-left">
                        <% if request.user.photo.attached? %>
                          <%= cl_image_tag(request.user.photo.key, class: "avatar-small") %>
                        <% else %>
                            <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "avatar-small") %>
                        <% end %>
                        <p style="margin-bottom: 0; padding: 0; height: 2rem; line-height: 2rem ">
                          <%= link_to request.user.username, user_path(request.user.id) %>
                        </p>
                      </div>
                    <% end %>
                  <%# end %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="container">
        <%= simple_form_for event, html: { class: "d-none", data: { edit_event_target: "form", action: "submit->edit-event#update" } } do |f| %>
          <%= f.label :hobby_id, 'Select a hobby' %>
          <div class="image-checkboxes" data-controller = "matching-modal">
            <% current_user.hobbies.each do |hobby| %>
              <% if hobby.photo.attached? %>
                <label >
                  <div class="image-checkbox" data-matching-modal-target="icon">
                    <%= cl_image_tag hobby.photo.key, class: "hobby-icon" %>
                    <%= f.check_box :hobby_id, { autocomplete: "hobby", data: { matching_modal_target: "checkbox", action: "change->matching-modal#toggle" } }, hobby.id, nil %>
                  </div>
                  <p class="hobby-name" data-matching-modal-target="name" ><%= hobby.name %></p>
                </label>
              <% end %>
            <% end %>
          </div>
          <%= f.input :name, input_html: { autocomplete: "off" } %>
          <%= f.input :location,
                required: true,
                autofocus: true,
                input_html: {data: {location_autocomplete_target:  "location"},class: "d-none"},
                wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
          <%= f.input :date, as: :string, input_html: { data: { controller: "datepicker" } } %>
          <%= f.input :description %>
          <%= f.submit class: "btn btn-form", value: "Save" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/events/_new.html.erb
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="eventAddModalLabel">New Event</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for event, html: { data: { add_event_target: "form", action: "submit->add-event#create" } } do |f| %>
               <%= f.label :hobby_id, 'Select a hobby' %>
            <div class="image-checkboxes" data-controller = "matching-modal">
              <% current_user.hobbies.each do |hobby| %>
                <% if hobby.photo.attached? %>
                    <label >
                      <div class="image-checkbox" data-matching-modal-target="icon">
                        <%= cl_image_tag hobby.photo.key, class: "hobby-icon" %>
                        <%= f.check_box :hobby_id, { autocomplete: "hobby", data: { matching_modal_target: "checkbox", action: "change->matching-modal#toggle" } }, hobby.id, nil %>
                      </div>
                      <p class="hobby-name" data-matching-modal-target="name" ><%= hobby.name %></p>
                      </label>
                    <% end %>
                  <% end %>
                </div>
              <%= f.input :name, input_html: { autocomplete: "off" }%>
              <%= f.input :location,
                required: true,
                autofocus: true,
                input_html: {data: {location_autocomplete_target:  "location"},class: "d-none"},
                wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
              <%= f.input :date, as: :string, input_html: { data: { controller: "datepicker" }}%>
              <%= f.input :description%>
              <%= f.submit class:"btn btn-form", value: "Add Event"%>
            <% end %>
          </div>
        </div>
      </div>

app/views/events/index.html.erb
<div class="container">
<div class="header-and-search">
<%= form_tag events_path, method: :get, class: "search-bar" do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Events", class: "search-input", autocomplete: "off" %>
  <%= button_tag type: 'submit', class: "search-button" do %>
    <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
    <% end %>
</div>
<div>
    <p class="index-text-top"><em>Events near you...</em></p>
</div>
    <div class="event-index-container">
    <% @events.order(:date).each do |event| %>
      <div class="event-card" data-bs-toggle="modal" data-bs-target="#eventDetailModal<%= event.id %>">
      <div class="d-flex align-items-center">
        <div class="user-hobby-icons-container d-flex p-3">
          <div class="event-hobby-icon-bg">
            <% if event.hobby && event.hobby.photo.attached? %>
              <%= cl_image_tag event.hobby.photo.key, class: "event-hobby-icon" %>
            <% end %>
          </div>
        </div>
        <div>
          <h5 style="margin-top: 0.5rem"><%= event.name %></h5>
          <p><%= event.location_by_city %></p>
          <p><%= event.date.strftime("%d %B %Y") %></p>
        </div>
      </div>
      </div>
      <div class="modal fade" id="eventDetailModal<%= event.id %>" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true" data-controller="edit-event">
      <%= render "events/event_modal", event: event%>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.js.erb
$("new").html("<%= escape_javascript(render 'users/show') %>");
$("#eventAddModal").modal('show');