config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:show, :index]

  resources :events, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :requests, only: [:new, :destroy] do
      member do
        patch :accept, to: "requests#accept", as: :accept_request
        patch :reject, to: "requests#reject", as: :reject_request
      end
    end
  end

  resources :chatrooms, only: [:index, :show, :new, :create, :update] do
    resources :messages, only: [:create]
  end


  resources :hobbies, only: [:index, :show]


end

app/models/hobby.rb
class Hobby < ApplicationRecord
  has_many :users, through: :selected_hobbies
  has_many :selected_hobbies
  has_many :events, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  def index
    if params[:search].present?
      @hobbies = Hobby.where("name ILIKE ?", "%#{params[:search]}%")
    else
      @hobbies = Hobby.all
    end
    @events = Event.all
    @users = User.all
    @selected_hobbies = SelectedHobby.all
    @buddies = current_user.chatrooms.map do |chatroom|
      chatroom.asker == current_user ? chatroom.receiver : chatroom.asker
    end
  end

  def show
    @hobby = Hobby.find(params[:id])
  end
end

app/views/hobbies/index.html.erb
<div class="container">

  <div class="header-and-search">
    <h1 class="text-center">Hobby Hub</h1>

    <%= form_tag hobbies_path, method: :get, class: "search-bar" do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Hobbies", class: "search-input", autocomplete: "off" %>
      <%= button_tag type: 'submit', class: "search-button" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>

  </div>

  <div class="hobby-hub-card-container">

    <% @hobbies.order(:name).each do |hobby| %>

      <div class="hobby-hub-card" data-bs-toggle="modal" data-bs-target="#hobbyModal<%= hobby.id %>">
        <div class="hobby-card-image">
          <% if hobby.photo.attached? %>
            <div class="icon-container"><%= cl_image_tag hobby.photo.key, width: "28px", height: "28px" %></div>
          <% else %>
            <%= hobby.name %>
          <% end %>
        </div>
        <div class="hobby-card-name">
          <p><%= hobby.name %></p>
        </div>
      </div>

      <div class="modal fade" id="hobbyModal<%= hobby.id %>" tabindex="-1" aria-labelledby="hobbyModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="hobby-modal-header">
              <div class="modal-image" style="margin-top: 3px">
                <div class="icon-container">
                <% if hobby.photo.attached? %>
                  <%= cl_image_tag hobby.photo.key, width: "30px", height: "30px" %>
                <% else %>
                  <%= hobby.name %>
                <% end %>
                </div>
              </div>
              <h1 class="modal-title fs-5" id="hobbyModalLabel text-center" style="height"><%= hobby.name %></h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <h2>Fans</h2>
              <div class="hobby-modal-users">
                <% list = @selected_hobbies.where(hobby_id: hobby.id) %>
                <% if list.length > 0 %>
                  <% list[0..4].each do |item| %>
                    <% if item.user.photo.attached? %>
                        <a href="users/<%= item.user.id %>">
                          <%= cl_image_tag item.user.photo.key  %>
                        </a>
                    <% else %>
                      <a href="users/<%= item.user.id %>">
                      <%= image_tag("https://cdn-icons-png.freepik.com/512/8742/8742495.png", class: "avatar-x-large border") %>
                      </a>
                    <% end %>
                  <% end %>
                <% else %>
                  <p style="color: grey !important"><em>no fans yet</em></p>
                <% end %>
              </div>
              <% if list.length > 5 %>
                <p class="see-all-link">
                 <em><%= link_to "See all #{hobby.name} Fans", users_path(search: hobby.name)%></em>
                </p>
              <% end %>
              <h2 style="margin-top: 16px">Events </h2>
              <% if @events.where(hobby_id: hobby.id).length > 0 %>
                <% @events.where(hobby_id: hobby.id)[0..2].each do |event| %>
                    <p style="border-bottom: solid #e3e3e3 1px; margin-bottom: 6px; padding-bottom: 6px"><a href="users/<%= event.user.id %>"><b><%= event.name %></b><br><em><%= event.location_by_city %></em><br><%= event.date.strftime("%d %B %Y") %></a></p>
                <% end %>
                <% if @events.where(hobby_id: hobby.id).length > 3 %>
                  <p class="see-all-link">
                    <em><%= link_to "See all #{hobby.name} Events", events_path(hobby_name: hobby.name)%></em>
                  </p>
                <% end %>
              <% else %>
                <p style="color: grey !important"><em>no events yet</em></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    <% end %>

  </div>

</div>

app/views/hobbies/show.html.erb
<div class="hobby-show-card-container align-center">

  <div class="hobby-show-top">

    <div class="hobby-show-top-icon">
      <%= cl_image_tag @hobby.photo.key, width: "90px", height: "90px" %>
    </div>

    <div class="hobby-show-top-text">
      <h1 class="text-center"><%= @hobby.name %></h1>
    </div>

  </div>

  <%# <hr class="rounded"> %>

  <div class="hobby-show-card-body">

    <div class="card-right">
      <h3>Fans</h3>
      <p>USER USER USER</p>
      <p>  X    X    X </p>
      <p>  X    X    X </p>
    </div>

    <div class="card-left">
      <h3>Events</h3>
      <p>Event 1</p>
      <p>Event 1</p>
      <p>Event 1</p>
    </div>

  </div>

</div>